# Generated by Django 4.2.14 on 2024-07-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tent',
            name='image',
        ),
        migrations.AddField(
            model_name='tent',
            name='photo',
            field=models.ImageField(default=1, upload_to='tent_photo/'),
            preserve_default=False,
        ),
    ]
