# Generated by Django 4.2.14 on 2024-07-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tents', '0004_profile_alter_tent_name_alter_tent_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
